# Generated by Django 5.2.3 on 2025-06-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
