# Generated by Django 5.2.3 on 2025-07-02 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_jobpost_hidden_jobrequest_staff_note_jobflag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('bulk_approve', 'Bulk Approve'), ('bulk_remove', 'Bulk Remove')], max_length=20)),
                ('target_type', models.CharField(choices=[('job_request', 'Job Request'), ('job', 'Job')], max_length=20)),
                ('target_ids', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
