# Generated by Django 5.2.3 on 2025-07-07 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_recentactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentactivity',
            name='action',
            field=models.CharField(choices=[('bulk_approve', 'Bulk Approve'), ('bulk_remove', 'Bulk Remove'), ('single_remove', 'Single Remove'), ('hide', 'Hide'), ('unhide', 'Unhide'), ('export_csv', 'Export CSV')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recentactivity',
            name='target_type',
            field=models.CharField(choices=[('job_request', 'Job Request'), ('job', 'Job'), ('export', 'Export')], max_length=20),
        ),
        migrations.CreateModel(
            name='BookedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.jobpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Booked Jobs',
                'unique_together': {('user', 'job')},
            },
        ),
    ]
