# Generated by Django 5.2.3 on 2025-07-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_alter_recentactivity_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='declared_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='delivery_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='destination_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='destination_zip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='height_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='length_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='origin_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='origin_zip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='pickup_time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='pickup_time_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='reference_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='special_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='volume_m3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='width_cm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
