# Generated by Django 5.2.3 on 2025-07-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='height_per_box_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='length_per_box_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='num_boxes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='weight_per_box_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='width_per_box_cm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
