# Generated by Django 5.2.3 on 2025-07-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_jobrequest_height_per_box_cm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
