# Generated by Django 5.2.3 on 2025-07-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_alter_jobpost_weight_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
